-- PromptVault 2.0: Seed 160 Prompts (Run ONLY if 002_categories.sql already ran)
-- This file is idempotent - safe to run multiple times

-- Coding Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('React Component Generator', 'Generate a modern, accessible React component with TypeScript interfaces, Tailwind CSS styling, responsive design, ARIA attributes, error loading states, and unit test template.\n\nComponent: [name]\nFunctionality: [description]', 'skill', 'community', '{coding,react,typescript,frontend}', 'MIT', 'published'),
('Python API Builder', 'Build a production-ready Python FastAPI endpoint with:\n1. Input validation (Pydantic)\n2. Error handling\n3. Rate limiting\n4. Documentation (OpenAPI)\n5. Unit tests\n\nEndpoint: [description]', 'skill', 'community', '{coding,python,api,backend}', 'MIT', 'published'),
('SQL Query Optimizer', 'Analyze and optimize this SQL query for performance:\n\n```sql\n[Paste query here]\n```\n\nProvide:\n1. Optimized version\n2. Index recommendations\n3. EXPLAIN plan analysis\n4. Alternative approaches', 'prompt', 'community', '{coding,sql,database,optimization}', 'MIT', 'published'),
('Code Review Assistant', 'Review the following code for bugs, performance issues, security vulnerabilities, and style. Provide line-by-line feedback with suggested fixes.\n\n```\n[Paste code here]\n```', 'skill', 'community', '{coding,review,best-practices}', 'MIT', 'published'),
('Docker Compose Setup', 'Create a production-ready Docker Compose configuration for:\n\nServices: [list services]\nRequirements: [specific needs]\n\nInclude:\n1. Health checks\n2. Volume mounts\n3. Environment variables\n4. Network configuration\n5. Restart policies', 'prompt', 'community', '{coding,docker,devops,deployment}', 'MIT', 'published'),
('JavaScript Debugging', 'Debug this JavaScript code and explain the issue:\n\n```javascript\n[Paste code here]\n```\n\nProvide:\n1. Root cause analysis\n2. Fixed code\n3. Prevention tips', 'prompt', 'community', '{coding,javascript,debugging}', 'MIT', 'published'),
('REST API Design', 'Design a RESTful API for [resource] with:\n1. Endpoints (GET, POST, PUT, DELETE)\n2. Request/Response schemas\n3. Authentication\n4. Error codes\n5. Pagination', 'prompt', 'community', '{coding,api,rest,backend}', 'MIT', 'published'),
('Git Workflow Guide', 'Explain the optimal Git workflow for:\n\nTeam size: [number]\nProject type: [type]\n\nInclude:\n1. Branching strategy\n2. Commit conventions\n3. PR review process\n4. Release workflow', 'prompt', 'community', '{coding,git,workflow,collaboration}', 'MIT', 'published'),
('CSS Layout Master', 'Create a CSS layout for:\n\nLayout: [description]\nBrowser support: [requirements]\n\nUse modern CSS (Grid/Flexbox) with fallbacks.', 'prompt', 'community', '{coding,css,frontend,layout}', 'MIT', 'published'),
('TypeScript Types Generator', 'Generate TypeScript types from this API response:\n\n```json\n[Paste JSON here]\n```\n\nInclude:\n1. Interface definitions\n2. Type guards\n3. Generic utilities', 'prompt', 'community', '{coding,typescript,types,api}', 'MIT', 'published'),
('Node.js Microservice', 'Build a Node.js microservice for [functionality] with:\n1. Express/Fastify setup\n2. Middleware (auth, logging, error handling)\n3. Database connection\n4. Health check endpoint\n5. Docker setup', 'skill', 'community', '{coding,nodejs,backend,microservice}', 'MIT', 'published'),
('React Native Screen', 'Create a React Native screen for [feature] with:\n1. Navigation setup\n2. State management\n3. API integration\n4. Loading/error states\n5. Responsive design', 'skill', 'community', '{coding,react-native,mobile}', 'MIT', 'published'),
('CI/CD Pipeline', 'Design a CI/CD pipeline for:\n\nPlatform: [GitHub Actions/GitLab CI]\nStack: [tech stack]\n\nInclude:\n1. Build steps\n2. Test automation\n3. Deployment stages\n4. Rollback strategy', 'prompt', 'community', '{coding,cicd,devops,automation}', 'MIT', 'published'),
('Data Structure Implementation', 'Implement a [data structure] in [language] with:\n1. Core operations\n2. Time complexity analysis\n3. Space complexity analysis\n4. Use cases', 'prompt', 'community', '{coding,algorithms,data-structures}', 'MIT', 'published'),
('Authentication System', 'Build an authentication system with:\n1. JWT tokens\n2. Refresh token rotation\n3. Role-based access\n4. Rate limiting\n5. Session management', 'skill', 'community', '{coding,security,authentication,jwt}', 'MIT', 'published'),
('WebSocket Real-time', 'Implement a WebSocket server for [use case] with:\n1. Connection handling\n2. Room/channel support\n3. Reconnection logic\n4. Message broadcasting', 'skill', 'community', '{coding,websocket,real-time,backend}', 'MIT', 'published'),
('GraphQL API Setup', 'Create a GraphQL API for [resource] with:\n1. Schema definition\n2. Resolvers\n3. Data loaders (N+1 prevention)\n4. Authentication middleware', 'skill', 'community', '{coding,graphql,api,backend}', 'MIT', 'published'),
('Testing Strategy', 'Design a testing strategy for:\n\nApplication: [description]\n\nInclude:\n1. Unit tests\n2. Integration tests\n3. E2E tests\n4. Test data management', 'prompt', 'community', '{coding,testing,qa,best-practices}', 'MIT', 'published'),
('Performance Optimization', 'Optimize this application for performance:\n\n```\n[Paste code/description]\n```\n\nFocus on:\n1. Load time\n2. Runtime efficiency\n3. Memory usage\n4. Bundle size', 'prompt', 'community', '{coding,performance,optimization}', 'MIT', 'published'),
('System Architecture Design', 'Design a system architecture for:\n\nRequirements: [description]\nScale: [expected load]\n\nInclude:\n1. Component diagram\n2. Data flow\n3. Technology choices\n4. Scaling strategy', 'workflow', 'community', '{coding,architecture,system-design}', 'MIT', 'published')
on conflict do nothing;

-- Writing Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('Blog Post Generator', 'Write a comprehensive, SEO-optimized blog post about [topic].\n\nInclude:\n1. Engaging introduction\n2. 5-7 H2/H3 subheadings\n3. Bullet points and lists\n4. FAQ section\n5. Call-to-action conclusion\n\nTarget keyword: [keyword]\nWord count: 1500-2000', 'prompt', 'community', '{writing,seo,blog,content}', 'MIT', 'published'),
('Viral Twitter Thread', 'Write a viral Twitter/X thread about [topic].\n\n- Hook: Bold claim or surprising stat\n- Body: 5-8 tweets with value\n- CTA: Drive engagement\n- Rules: One idea per tweet, line breaks', 'prompt', 'community', '{writing,social-media,marketing}', 'MIT', 'published'),
('Email Sequence Creator', 'Create a 5-email nurture sequence for:\n\nProduct: [description]\nAudience: [target]\n\nInclude:\n1. Subject lines\n2. Preview text\n3. Body copy\n4. CTAs\n5. Send timing', 'prompt', 'community', '{writing,email,marketing,sequence}', 'MIT', 'published'),
('Landing Page Copy', 'Write landing page copy for:\n\nProduct: [description]\nTarget audience: [audience]\n\nInclude:\n1. Headline + subheadline\n2. Hero section\n3. Features/benefits\n4. Social proof\n5. CTA sections', 'prompt', 'community', '{writing,copywriting,landing-page,marketing}', 'MIT', 'published'),
('Product Description', 'Write compelling product descriptions for:\n\nProduct: [name]\nFeatures: [list]\n\nCreate 3 versions:\n1. Short (50 words)\n2. Medium (150 words)\n3. Long (300 words)', 'prompt', 'community', '{writing,copywriting,ecommerce}', 'MIT', 'published'),
('Press Release Writer', 'Write a press release for:\n\nNews: [announcement]\nCompany: [description]\n\nInclude:\n1. Headline\n2. Dateline\n3. Lead paragraph\n4. Body\n5. Boilerplate\n6. Contact info', 'prompt', 'community', '{writing,pr,communications}', 'MIT', 'published'),
('Case Study Creator', 'Write a case study for:\n\nClient: [name]\nChallenge: [problem]\nSolution: [what you did]\nResults: [outcomes]\n\nInclude:\n1. Executive summary\n2. Challenge\n3. Solution\n4. Results\n5. Testimonial', 'prompt', 'community', '{writing,case-study,marketing}', 'MIT', 'published'),
('White Paper Outline', 'Create a detailed white paper outline for:\n\nTopic: [subject]\nAudience: [target]\n\nInclude:\n1. Executive summary\n2. Problem statement\n3. Solution overview\n4. Technical details\n5. Case studies\n6. Conclusion', 'prompt', 'community', '{writing,white-paper,b2b}', 'MIT', 'published'),
('Video Script Writer', 'Write a video script for:\n\nTopic: [subject]\nDuration: [length]\nPlatform: [YouTube/TikTok/etc]\n\nInclude:\n1. Hook (first 5 seconds)\n2. Main content\n3. B-roll suggestions\n4. CTA', 'prompt', 'community', '{writing,video,script,content}', 'MIT', 'published'),
('Podcast Show Notes', 'Create podcast show notes for:\n\nEpisode: [title]\nTopics: [list]\nGuests: [names]\n\nInclude:\n1. Episode summary\n2. Key takeaways\n3. Timestamps\n4. Links mentioned\n5. Guest bios', 'prompt', 'community', '{writing,podcast,show-notes}', 'MIT', 'published'),
('Technical Documentation', 'Write technical documentation for:\n\nFeature/API: [description]\nAudience: [developers/users]\n\nInclude:\n1. Overview\n2. Getting started\n3. API reference\n4. Examples\n5. Troubleshooting', 'skill', 'community', '{writing,documentation,technical}', 'MIT', 'published'),
('User Story Writer', 'Write user stories for:\n\nFeature: [description]\n\nFormat:\n- As a [user type]\n- I want [goal]\n- So that [benefit]\n\nInclude acceptance criteria for each.', 'prompt', 'community', '{writing,agile,product}', 'MIT', 'published'),
('Error Message Copy', 'Write user-friendly error messages for:\n\nScenario: [description]\n\nInclude:\n1. Clear problem statement\n2. Suggested fix\n3. Support contact\n4. Error code reference', 'prompt', 'community', '{writing,ux,error-messages}', 'MIT', 'published'),
('FAQ Page Creator', 'Create an FAQ page for:\n\nProduct/Service: [description]\n\nInclude:\n1. 10-15 common questions\n2. Clear, concise answers\n3. CTA at the end\n4. Search-friendly format', 'prompt', 'community', '{writing,faq,support}', 'MIT', 'published'),
('About Page Writer', 'Write an About page for:\n\nCompany/Person: [description]\n\nInclude:\n1. Origin story\n2. Mission/values\n3. Team intro\n4. Achievements\n5. Future vision', 'prompt', 'community', '{writing,about,brand}', 'MIT', 'published'),
('Newsletter Content', 'Create newsletter content for:\n\nTopic: [subject]\nAudience: [subscribers]\n\nInclude:\n1. Subject line\n2. Preview text\n3. Main story\n4. Quick links\n5. CTA', 'prompt', 'community', '{writing,newsletter,email}', 'MIT', 'published'),
('Ebook Outline', 'Create a detailed ebook outline for:\n\nTopic: [subject]\nTarget audience: [readers]\n\nInclude:\n1. Chapter titles\n2. Key points per chapter\n3. Case studies\n4. Action items', 'prompt', 'community', '{writing,ebook,content}', 'MIT', 'published'),
('Ad Copy Generator', 'Write ad copy for:\n\nPlatform: [Google/Facebook/LinkedIn]\nProduct: [description]\nGoal: [conversions/clicks]\n\nCreate 5 variations with different angles.', 'prompt', 'community', '{writing,advertising,copywriting}', 'MIT', 'published'),
('Product Hunt Launch', 'Create a Product Hunt launch for:\n\nProduct: [name]\nTagline: [one-liner]\n\nInclude:\n1. First comment (maker comment)\n2. Description\n3. Key features\n4. Launch offers', 'prompt', 'community', '{writing,product-hunt,launch}', 'MIT', 'published'),
('Grant Proposal Writer', 'Write a grant proposal for:\n\nProject: [description]\nFunding amount: [amount]\n\nInclude:\n1. Executive summary\n2. Problem statement\n3. Objectives\n4. Methodology\n5. Budget', 'prompt', 'community', '{writing,grant,proposal}', 'MIT', 'published')
on conflict do nothing;

-- Business Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('Business Model Canvas', 'Create a business model canvas for:\n\nBusiness: [description]\n\nFill all 9 blocks:\n1. Customer segments\n2. Value propositions\n3. Channels\n4. Customer relationships\n5. Revenue streams\n6. Key resources\n7. Key activities\n8. Key partners\n9. Cost structure', 'prompt', 'community', '{business,strategy,canvas}', 'MIT', 'published'),
('Competitor Analysis', 'Analyze competitors for:\n\nProduct/Service: [description]\n\nFor each competitor provide:\n1. Overview\n2. Strengths/weaknesses\n3. Pricing\n4. Market position\n5. Key differentiators', 'prompt', 'community', '{business,competitive-analysis,marketing}', 'MIT', 'published'),
('Customer Persona Builder', 'Create detailed customer personas for:\n\nProduct/Service: [description]\n\nFor each persona include:\n1. Demographics\n2. Psychographics\n3. Goals\n4. Pain points\n5. Buying behavior', 'prompt', 'community', '{business,persona,marketing}', 'MIT', 'published'),
('Sales Pitch Creator', 'Create a sales pitch for:\n\nProduct: [description]\nProspect: [type]\n\nInclude:\n1. Hook\n2. Problem agitation\n3. Solution presentation\n4. Social proof\n5. CTA', 'prompt', 'community', '{business,sales,pitch}', 'MIT', 'published'),
('Marketing Plan Template', 'Create a marketing plan for:\n\nProduct: [description]\nBudget: [amount]\nTimeline: [period]\n\nInclude:\n1. Goals\n2. Target audience\n3. Channels\n4. Tactics\n5. Budget allocation\n6. KPIs', 'prompt', 'community', '{business,marketing,planning}', 'MIT', 'published'),
('Email Marketing Campaign', 'Design an email marketing campaign for:\n\nGoal: [objective]\nAudience: [segment]\n\nInclude:\n1. Campaign strategy\n2. Email sequence\n3. Subject lines\n4. Content calendar\n5. Metrics to track', 'prompt', 'community', '{business,email,campaign}', 'MIT', 'published'),
('Social Media Strategy', 'Create a social media strategy for:\n\nBrand: [description]\nPlatforms: [list]\n\nInclude:\n1. Content pillars\n2. Posting schedule\n3. Content types\n4. Engagement tactics\n5. Growth metrics', 'prompt', 'community', '{business,social-media,strategy}', 'MIT', 'published'),
('Pricing Strategy', 'Develop a pricing strategy for:\n\nProduct: [description]\nMarket: [competitors]\n\nInclude:\n1. Pricing models\n2. Tier structure\n3. Discount strategy\n4. Competitive analysis\n5. Revenue projections', 'prompt', 'community', '{business,pricing,strategy}', 'MIT', 'published'),
('Customer Onboarding Flow', 'Design a customer onboarding flow for:\n\nProduct: [description]\n\nInclude:\n1. Welcome sequence\n2. First-time setup\n3. Key milestones\n4. Success metrics\n5. Support touchpoints', 'prompt', 'community', '{business,onboarding,ux}', 'MIT', 'published'),
('KPI Dashboard Design', 'Design a KPI dashboard for:\n\nBusiness: [description]\n\nInclude:\n1. North star metric\n2. Leading indicators\n3. Lagging indicators\n4. Visualization types\n5. Update frequency', 'prompt', 'community', '{business,kpi,metrics}', 'MIT', 'published'),
('Hiring Job Description', 'Write a job description for:\n\nRole: [title]\nCompany: [description]\n\nInclude:\n1. Role overview\n2. Responsibilities\n3. Requirements\n4. Nice-to-haves\n5. Company culture', 'prompt', 'community', '{business,hr,hiring}', 'MIT', 'published'),
('Performance Review Template', 'Create a performance review template for:\n\nRole: [title]\n\nInclude:\n1. Self-assessment\n2. Manager assessment\n3. Goal review\n4. Development areas\n5. Next period goals', 'prompt', 'community', '{business,hr,review}', 'MIT', 'published'),
('Vendor Evaluation', 'Create a vendor evaluation matrix for:\n\nService/Product: [description]\n\nInclude:\n1. Evaluation criteria\n2. Weight assignments\n3. Scoring rubric\n4. Comparison table\n5. Recommendation format', 'prompt', 'community', '{business,vendor,procurement}', 'MIT', 'published'),
('Crisis Communication Plan', 'Create a crisis communication plan for:\n\nScenario: [description]\n\nInclude:\n1. Response team\n2. Communication channels\n3. Message templates\n4. Escalation process\n5. Post-crisis review', 'prompt', 'community', '{business,crisis,communications}', 'MIT', 'published'),
('Partnership Proposal', 'Write a partnership proposal for:\n\nPartner: [description]\nCollaboration: [type]\n\nInclude:\n1. Executive summary\n2. Mutual benefits\n3. Proposed structure\n4. Revenue sharing\n5. Next steps', 'prompt', 'community', '{business,partnership,proposal}', 'MIT', 'published'),
('Customer Feedback Survey', 'Create a customer feedback survey for:\n\nProduct: [description]\nGoal: [objective]\n\nInclude:\n1. Survey questions\n2. Response scales\n3. Open-ended questions\n4. Incentive structure', 'prompt', 'community', '{business,feedback,research}', 'MIT', 'published'),
('Revenue Forecast Model', 'Create a revenue forecast model for:\n\nBusiness: [description]\nPeriod: [timeframe]\n\nInclude:\n1. Assumptions\n2. Growth drivers\n3. Monthly projections\n4. Best/worst case\n5. Key metrics', 'prompt', 'community', '{business,forecast,finance}', 'MIT', 'published'),
('Brand Guidelines', 'Create brand guidelines for:\n\nBrand: [description]\n\nInclude:\n1. Mission/vision\n2. Brand voice\n3. Color palette\n4. Typography\n5. Logo usage', 'prompt', 'community', '{business,brand,guidelines}', 'MIT', 'published'),
('Customer Retention Strategy', 'Develop a customer retention strategy for:\n\nProduct: [description]\n\nInclude:\n1. Churn analysis\n2. Retention tactics\n3. Loyalty programs\n4. Win-back campaigns\n5. Success metrics', 'prompt', 'community', '{business,retention,strategy}', 'MIT', 'published'),
('Market Entry Strategy', 'Create a market entry strategy for:\n\nProduct: [description]\nMarket: [target]\n\nInclude:\n1. Market analysis\n2. Entry approach\n3. Go-to-market plan\n4. Resource requirements\n5. Risk assessment', 'prompt', 'community', '{business,market-entry,strategy}', 'MIT', 'published')
on conflict do nothing;

-- Creative Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('Midjourney Portrait Prompt', 'Create a photorealistic portrait:\n\n- Subject: [description]\n- Lighting: Soft natural window light\n- Camera: 85mm, f/1.8\n- Style: Magazine editorial\n- Background: [bokeh/plain]\n\n--ar 3:4 --style raw --s 250', 'prompt', 'community', '{creative,midjourney,photography}', 'CC0', 'published'),
('DALL-E Image Prompt', 'Generate an image of:\n\nSubject: [description]\nStyle: [artistic style]\nMood: [atmosphere]\nComposition: [layout]\n\nBe specific about colors, lighting, and details.', 'prompt', 'community', '{creative,dall-e,image-generation}', 'CC0', 'published'),
('Logo Design Brief', 'Create a logo design brief for:\n\nBrand: [description]\n\nInclude:\n1. Brand personality\n2. Target audience\n3. Color preferences\n4. Style references\n5. Usage requirements', 'prompt', 'community', '{creative,logo,design}', 'CC0', 'published'),
('UI/UX Wireframe Description', 'Describe a wireframe for:\n\nScreen: [description]\nPlatform: [web/mobile]\n\nInclude:\n1. Layout structure\n2. Key components\n3. Navigation\n4. User flow\n5. Interactions', 'prompt', 'community', '{creative,ui-ux,wireframe}', 'CC0', 'published'),
('Color Palette Generator', 'Create a color palette for:\n\nProject: [description]\nMood: [atmosphere]\n\nInclude:\n1. Primary colors\n2. Secondary colors\n3. Accent colors\n4. Neutral tones\n5. Usage guidelines', 'prompt', 'community', '{creative,color,design}', 'CC0', 'published'),
('Typography Pairing', 'Suggest typography pairings for:\n\nProject: [description]\nStyle: [modern/classic/etc]\n\nInclude:\n1. Heading font\n2. Body font\n3. Accent font\n4. Size scale\n5. Usage examples', 'prompt', 'community', '{creative,typography,design}', 'CC0', 'published'),
('Video Storyboard', 'Create a storyboard for:\n\nVideo: [description]\nDuration: [length]\n\nInclude:\n1. Scene descriptions\n2. Camera angles\n3. Transitions\n4. Audio notes\n5. Text overlays', 'prompt', 'community', '{creative,video,storyboard}', 'CC0', 'published'),
('Music Composition Prompt', 'Compose music for:\n\nMood: [atmosphere]\nGenre: [style]\nDuration: [length]\n\nInclude:\n1. Tempo\n2. Key\n3. Instrumentation\n4. Structure\n5. Dynamics', 'prompt', 'community', '{creative,music,composition}', 'CC0', 'published'),
('Character Design', 'Design a character for:\n\nProject: [description]\nStyle: [artistic style]\n\nInclude:\n1. Physical appearance\n2. Personality traits\n3. Backstory\n4. Costume details\n5. Expression sheet', 'prompt', 'community', '{creative,character,design}', 'CC0', 'published'),
('World Building', 'Create a world for:\n\nStory/Game: [description]\n\nInclude:\n1. Geography\n2. Culture\n3. History\n4. Magic/Technology\n5. Key locations', 'prompt', 'community', '{creative,worldbuilding,fiction}', 'CC0', 'published'),
('Instagram Carousel Design', 'Design an Instagram carousel for:\n\nTopic: [subject]\nBrand: [description]\n\nInclude:\n1. Slide-by-slide content\n2. Visual direction\n3. Caption\n4. Hashtags\n5. CTA', 'prompt', 'community', '{creative,instagram,design}', 'CC0', 'published'),
('Podcast Cover Art', 'Create podcast cover art for:\n\nPodcast: [name]\nGenre: [category]\n\nInclude:\n1. Concept\n2. Color scheme\n3. Typography\n4. Imagery\n5. Platform requirements', 'prompt', 'community', '{creative,podcast,art}', 'CC0', 'published'),
('Animation Prompt', 'Create an animation for:\n\nScene: [description]\nStyle: [2D/3D/etc]\nDuration: [length]\n\nInclude:\n1. Keyframes\n2. Motion description\n3. Timing\n4. Transitions', 'prompt', 'community', '{creative,animation,motion}', 'CC0', 'published'),
('Photography Composition', 'Plan a photoshoot for:\n\nSubject: [description]\nStyle: [type]\n\nInclude:\n1. Shot list\n2. Lighting setup\n3. Composition notes\n4. Props\n5. Post-processing direction', 'prompt', 'community', '{creative,photography,composition}', 'CC0', 'published'),
('NFT Collection Concept', 'Create an NFT collection concept:\n\nTheme: [description]\nSize: [number]\n\nInclude:\n1. Art style\n2. Traits/layers\n3. Rarity system\n4. Utility\n5. Story', 'prompt', 'community', '{creative,nft,art}', 'CC0', 'published'),
('Album Cover Design', 'Design an album cover for:\n\nArtist: [name]\nGenre: [style]\nMood: [atmosphere]\n\nInclude:\n1. Concept\n2. Color palette\n3. Typography\n4. Imagery\n5. Layout', 'prompt', 'community', '{creative,album,cover}', 'CC0', 'published'),
('Interior Design Prompt', 'Design an interior space for:\n\nRoom: [type]\nStyle: [description]\nBudget: [range]\n\nInclude:\n1. Color scheme\n2. Furniture\n3. Lighting\n4. Accessories\n5. Layout', 'prompt', 'community', '{creative,interior,design}', 'CC0', 'published'),
('Fashion Mood Board', 'Create a fashion mood board for:\n\nCollection: [description]\nSeason: [time]\n\nInclude:\n1. Color palette\n2. Fabric suggestions\n3. Silhouettes\n4. Inspiration references\n5. Key pieces', 'prompt', 'community', '{creative,fashion,moodboard}', 'CC0', 'published'),
('Tattoo Design Brief', 'Create a tattoo design brief for:\n\nStyle: [description]\nPlacement: [body part]\nSize: [dimensions]\n\nInclude:\n1. Design elements\n2. Line work\n3. Shading style\n4. Color palette\n5. Reference images', 'prompt', 'community', '{creative,tattoo,design}', 'CC0', 'published'),
('Architecture Visualization', 'Create an architecture visualization for:\n\nBuilding: [description]\nStyle: [modern/classic/etc]\n\nInclude:\n1. Exterior view\n2. Key features\n3. Materials\n4. Surroundings\n5. Lighting', 'prompt', 'community', '{creative,architecture,visualization}', 'CC0', 'published')
on conflict do nothing;

-- Education Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('Lesson Plan Creator', 'Create a lesson plan for:\n\nTopic: [subject]\nGrade Level: [level]\nDuration: [time]\n\nInclude:\n1. Learning objectives\n2. Materials needed\n3. Introduction (10 min)\n4. Main activity (20 min)\n5. Assessment (10 min)', 'prompt', 'community', '{education,lesson-plan,teaching}', 'MIT', 'published'),
('Quiz Generator', 'Create a quiz for:\n\nTopic: [subject]\nDifficulty: [easy/medium/hard]\n\nInclude:\n1. 10 multiple choice questions\n2. 5 true/false questions\n3. 3 short answer questions\n4. Answer key\n5. Explanations', 'prompt', 'community', '{education,quiz,assessment}', 'MIT', 'published'),
('Study Guide Builder', 'Create a study guide for:\n\nSubject: [topic]\nExam: [type]\n\nInclude:\n1. Key concepts\n2. Important terms\n3. Practice questions\n4. Memory aids\n5. Review schedule', 'prompt', 'community', '{education,study-guide,exam}', 'MIT', 'published'),
('Essay Grading Rubric', 'Create an essay grading rubric for:\n\nAssignment: [description]\nGrade Level: [level]\n\nInclude:\n1. Criteria categories\n2. Point values\n3. Performance levels\n4. Feedback prompts\n5. Overall assessment', 'prompt', 'community', '{education,grading,rubric}', 'MIT', 'published'),
('Language Practice Conversation', 'Create a conversation practice for:\n\nLanguage: [target]\nLevel: [beginner/intermediate/advanced]\nTopic: [subject]\n\nInclude:\n1. Dialogue\n2. Vocabulary\n3. Grammar focus\n4. Comprehension questions\n5. Role-play prompts', 'prompt', 'community', '{education,language,practice}', 'MIT', 'published'),
('Math Problem Solver', 'Solve this math problem step-by-step:\n\nProblem: [description]\nLevel: [grade]\n\nInclude:\n1. Problem restatement\n2. Solution steps\n3. Key concepts\n4. Final answer\n5. Verification', 'prompt', 'community', '{education,math,problem-solving}', 'MIT', 'published'),
('Science Experiment Design', 'Design a science experiment for:\n\nTopic: [subject]\nGrade Level: [level]\n\nInclude:\n1. Hypothesis\n2. Materials\n3. Procedure\n4. Data collection\n5. Analysis method', 'prompt', 'community', '{education,science,experiment}', 'MIT', 'published'),
('History Timeline Creator', 'Create a timeline for:\n\nPeriod/Event: [description]\n\nInclude:\n1. Key dates\n2. Major events\n3. Important figures\n4. Cause and effect\n5. Significance', 'prompt', 'community', '{education,history,timeline}', 'MIT', 'published'),
('Reading Comprehension', 'Create reading comprehension questions for:\n\nText: [passage]\nGrade Level: [level]\n\nInclude:\n1. Main idea questions\n2. Detail questions\n3. Inference questions\n4. Vocabulary questions\n5. Critical thinking questions', 'prompt', 'community', '{education,reading,comprehension}', 'MIT', 'published'),
('Project-Based Learning', 'Design a project-based learning activity for:\n\nTopic: [subject]\nDuration: [timeframe]\n\nInclude:\n1. Driving question\n2. Learning goals\n3. Project phases\n4. Deliverables\n5. Assessment criteria', 'prompt', 'community', '{education,pbl,project}', 'MIT', 'published'),
('Flashcard Generator', 'Create flashcards for:\n\nTopic: [subject]\nNumber: [count]\n\nInclude:\n1. Term/concept\n2. Definition/explanation\n3. Example\n4. Mnemonic (if applicable)\n5. Related terms', 'prompt', 'community', '{education,flashcards,study}', 'MIT', 'published'),
('Debate Preparation', 'Prepare for a debate on:\n\nTopic: [subject]\nPosition: [for/against]\n\nInclude:\n1. Main arguments\n2. Supporting evidence\n3. Counterarguments\n4. Rebuttals\n5. Closing statement', 'prompt', 'community', '{education,debate,critical-thinking}', 'MIT', 'published'),
('Field Trip Plan', 'Plan a field trip to:\n\nDestination: [place]\nGrade Level: [level]\n\nInclude:\n1. Learning objectives\n2. Pre-trip activities\n3. During-trip tasks\n4. Post-trip reflection\n5. Assessment', 'prompt', 'community', '{education,field-trip,planning}', 'MIT', 'published'),
('Parent-Teacher Conference', 'Prepare for a parent-teacher conference about:\n\nStudent: [description]\n\nInclude:\n1. Student strengths\n2. Areas for growth\n3. Specific examples\n4. Goals\n5. Support strategies', 'prompt', 'community', '{education,conference,communication}', 'MIT', 'published'),
('Online Course Outline', 'Create an online course outline for:\n\nSubject: [topic]\nLevel: [beginner/advanced]\n\nInclude:\n1. Course objectives\n2. Module structure\n3. Lesson topics\n4. Assessments\n5. Resources', 'prompt', 'community', '{education,online,course}', 'MIT', 'published'),
('Homework Helper', 'Help with this homework problem:\n\nSubject: [topic]\nProblem: [description]\n\nProvide:\n1. Step-by-step solution\n2. Explanation of concepts\n3. Similar practice problems\n4. Tips for understanding', 'prompt', 'community', '{education,homework,help}', 'MIT', 'published'),
('College Application Essay', 'Write a college application essay for:\n\nPrompt: [essay question]\nStudent: [background]\n\nInclude:\n1. Hook\n2. Personal story\n3. Growth/learning\n4. Future goals\n5. Conclusion', 'prompt', 'community', '{education,college,essay}', 'MIT', 'published'),
('STEM Activity', 'Design a STEM activity for:\n\nTopic: [subject]\nAge Group: [range]\n\nInclude:\n1. Learning objectives\n2. Materials\n3. Instructions\n4. STEM connections\n5. Extension ideas', 'prompt', 'community', '{education,stem,activity}', 'MIT', 'published'),
('Special Accommodation Plan', 'Create an accommodation plan for:\n\nStudent Need: [description]\n\nInclude:\n1. Accommodations\n2. Modifications\n3. Goals\n4. Progress monitoring\n5. Review schedule', 'prompt', 'community', '{education,iep,accommodation}', 'MIT', 'published'),
('Virtual Field Trip', 'Design a virtual field trip to:\n\nDestination: [place]\nGrade Level: [level]\n\nInclude:\n1. Pre-trip introduction\n2. Virtual exploration\n3. Interactive activities\n4. Discussion questions\n5. Follow-up project', 'prompt', 'community', '{education,virtual,field-trip}', 'MIT', 'published')
on conflict do nothing;

-- Productivity Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('Daily Planner Template', 'Create a daily planner for:\n\nDate: [date]\nPriorities: [list]\n\nInclude:\n1. Morning routine\n2. Time blocks\n3. Priority tasks\n4. Breaks\n5. Evening review', 'prompt', 'community', '{productivity,planning,daily}', 'MIT', 'published'),
('Weekly Review', 'Conduct a weekly review for:\n\nWeek: [dates]\n\nInclude:\n1. Accomplishments\n2. Challenges\n3. Lessons learned\n4. Next week priorities\n5. Habit tracker', 'prompt', 'community', '{productivity,review,weekly}', 'MIT', 'published'),
('Email Management System', 'Create an email management system:\n\nInbox: [description]\n\nInclude:\n1. Folder structure\n2. Filter rules\n3. Response templates\n4. Priority system\n5. Daily schedule', 'prompt', 'community', '{productivity,email,management}', 'MIT', 'published'),
('Meeting Agenda Creator', 'Create a meeting agenda for:\n\nMeeting: [type]\nDuration: [time]\nAttendees: [list]\n\nInclude:\n1. Objectives\n2. Topics with time allocations\n3. Pre-reading\n4. Action items\n5. Follow-up', 'prompt', 'community', '{productivity,meeting,agenda}', 'MIT', 'published'),
('Note-Taking System', 'Design a note-taking system for:\n\nContext: [work/study/etc]\n\nInclude:\n1. Note structure\n2. Organization method\n3. Tagging system\n4. Review process\n5. Search tips', 'prompt', 'community', '{productivity,notes,organization}', 'MIT', 'published'),
('Goal Setting Framework', 'Set goals using SMART framework:\n\nArea: [life/career/etc]\n\nInclude:\n1. Specific goals\n2. Measurable outcomes\n3. Achievable steps\n4. Relevant connections\n5. Time-bound deadlines', 'prompt', 'community', '{productivity,goals,planning}', 'MIT', 'published'),
('Time Blocking Schedule', 'Create a time blocking schedule for:\n\nDay: [type]\nCommitments: [list]\n\nInclude:\n1. Deep work blocks\n2. Shallow work blocks\n3. Break times\n4. Buffer time\n5. Flexibility tips', 'prompt', 'community', '{productivity,time-blocking,schedule}', 'MIT', 'published'),
('Decision Matrix', 'Create a decision matrix for:\n\nDecision: [description]\nOptions: [list]\n\nInclude:\n1. Criteria\n2. Weight assignments\n3. Scoring\n4. Results\n5. Recommendation', 'prompt', 'community', '{productivity,decision,matrix}', 'MIT', 'published'),
('Habit Tracker Design', 'Design a habit tracker for:\n\nHabits: [list]\nDuration: [timeframe]\n\nInclude:\n1. Daily checklist\n2. Streak counter\n3. Reward system\n4. Accountability\n5. Progress visualization', 'prompt', 'community', '{productivity,habits,tracker}', 'MIT', 'published'),
('Project Kickoff', 'Plan a project kickoff for:\n\nProject: [description]\nTeam: [members]\n\nInclude:\n1. Project overview\n2. Roles/responsibilities\n3. Timeline\n4. Communication plan\n5. Success metrics', 'prompt', 'community', '{productivity,project,kickoff}', 'MIT', 'published'),
('Delegation Framework', 'Create a delegation framework for:\n\nTasks: [list]\nTeam: [members]\n\nInclude:\n1. Task assessment\n2. Matching skills to tasks\n3. Instructions template\n4. Check-in schedule\n5. Feedback loop', 'prompt', 'community', '{productivity,delegation,management}', 'MIT', 'published'),
('Focus Session Planner', 'Plan a focus session for:\n\nTask: [description]\nDuration: [length]\n\nInclude:\n1. Preparation\n2. Environment setup\n3. Pomodoro structure\n4. Distraction management\n5. Break activities', 'prompt', 'community', '{productivity,focus,deep-work}', 'MIT', 'published'),
('Weekly Meal Planner', 'Create a weekly meal plan for:\n\nDietary: [restrictions]\nPeople: [number]\n\nInclude:\n1. Meal schedule\n2. Recipe list\n3. Shopping list\n4. Prep schedule\n5. Budget estimate', 'prompt', 'community', '{productivity,meal,planning}', 'MIT', 'published'),
('Travel Itinerary', 'Plan a travel itinerary for:\n\nDestination: [place]\nDuration: [days]\n\nInclude:\n1. Day-by-day schedule\n2. Activities\n3. Transportation\n4. Accommodation\n5. Budget', 'prompt', 'community', '{productivity,travel,planning}', 'MIT', 'published'),
('Budget Tracker', 'Create a monthly budget tracker:\n\nIncome: [amount]\nExpenses: [categories]\n\nInclude:\n1. Income tracking\n2. Expense categories\n3. Savings goals\n4. Spending alerts\n5. Monthly summary', 'prompt', 'community', '{productivity,budget,finance}', 'MIT', 'published'),
('Morning Routine Optimizer', 'Optimize a morning routine:\n\nWake time: [time]\nGoals: [list]\n\nInclude:\n1. Wake-up routine\n2. Exercise\n3. Mindfulness\n4. Learning\n5. Day preview', 'prompt', 'community', '{productivity,morning,routine}', 'MIT', 'published'),
('Evening Wind-Down', 'Create an evening wind-down routine:\n\nBedtime: [time]\n\nInclude:\n1. Screen curfew\n2. Reflection\n3. Next-day prep\n4. Relaxation\n5. Sleep hygiene', 'prompt', 'community', '{productivity,evening,routine}', 'MIT', 'published'),
('Digital Declutter', 'Plan a digital declutter:\n\nAreas: [devices/accounts/etc]\n\nInclude:\n1. File organization\n2. Email cleanup\n3. App audit\n4. Password management\n5. Maintenance schedule', 'prompt', 'community', '{productivity,digital,organization}', 'MIT', 'published'),
('Networking Strategy', 'Create a networking strategy:\n\nGoal: [objective]\nIndustry: [field]\n\nInclude:\n1. Target contacts\n2. Outreach templates\n3. Follow-up system\n4. Value offering\n5. Relationship tracking', 'prompt', 'community', '{productivity,networking,career}', 'MIT', 'published'),
('Side Hustle Planner', 'Plan a side hustle:\n\nIdea: [description]\nTime available: [hours/week]\n\nInclude:\n1. Business model\n2. Time commitment\n3. Revenue streams\n4. Marketing plan\n5. Growth milestones', 'prompt', 'community', '{productivity,side-hustle,business}', 'MIT', 'published')
on conflict do nothing;

-- Self Improvement Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('Meditation Guide', 'Create a meditation practice for:\n\nExperience: [beginner/intermediate]\nGoal: [focus/calm/etc]\n\nInclude:\n1. Technique\n2. Duration\n3. Frequency\n4. Progression\n5. Troubleshooting', 'prompt', 'community', '{self-improvement,meditation,mindfulness}', 'MIT', 'published'),
('Journaling Prompts', 'Create journaling prompts for:\n\nFocus: [area]\nDuration: [timeframe]\n\nInclude:\n1. Daily prompts\n2. Weekly reflection\n3. Monthly review\n4. Gratitude practice\n5. Goal tracking', 'prompt', 'community', '{self-improvement,journaling,reflection}', 'MIT', 'published'),
('Confidence Builder', 'Create a confidence building plan:\n\nArea: [specific]\nCurrent level: [description]\n\nInclude:\n1. Small wins\n2. Skill building\n3. Positive self-talk\n4. Body language\n5. Challenge ladder', 'prompt', 'community', '{self-improvement,confidence,mindset}', 'MIT', 'published'),
('Stress Management', 'Create a stress management plan:\n\nSources: [list]\n\nInclude:\n1. Identification\n2. Coping strategies\n3. Relaxation techniques\n4. Boundaries\n5. Support system', 'prompt', 'community', '{self-improvement,stress,wellness}', 'MIT', 'published'),
('Public Speaking Guide', 'Create a public speaking improvement plan:\n\nCurrent level: [description]\nGoal: [specific]\n\nInclude:\n1. Practice exercises\n2. Anxiety management\n3. Speech structure\n4. Delivery tips\n5. Feedback methods', 'prompt', 'community', '{self-improvement,speaking,communication}', 'MIT', 'published'),
('Reading Habit Builder', 'Build a reading habit:\n\nGoal: [books/month]\nPreferences: [genres]\n\nInclude:\n1. Book list\n2. Reading schedule\n3. Note-taking method\n4. Discussion/review\n5. Tracking system', 'prompt', 'community', '{self-improvement,reading,habits}', 'MIT', 'published'),
('Fitness Plan Creator', 'Create a fitness plan for:\n\nGoal: [description]\nLevel: [beginner/intermediate/advanced]\n\nInclude:\n1. Workout schedule\n2. Exercise selection\n3. Progression\n4. Nutrition basics\n5. Recovery', 'prompt', 'community', '{self-improvement,fitness,health}', 'MIT', 'published'),
('Sleep Optimization', 'Optimize sleep quality:\n\nCurrent issues: [description]\n\nInclude:\n1. Sleep hygiene\n2. Environment optimization\n3. Evening routine\n4. Morning routine\n5. Tracking', 'prompt', 'community', '{self-improvement,sleep,health}', 'MIT', 'published'),
('Anger Management', 'Create an anger management plan:\n\nTriggers: [list]\n\nInclude:\n1. Recognition signs\n2. De-escalation techniques\n3. Communication strategies\n4. Cool-down methods\n5. Prevention', 'prompt', 'community', '{self-improvement,anger,emotions}', 'MIT', 'published'),
('Financial Literacy', 'Create a financial literacy plan:\n\nCurrent knowledge: [level]\nGoals: [specific]\n\nInclude:\n1. Budgeting basics\n2. Saving strategies\n3. Investing intro\n4. Debt management\n5. Resources', 'prompt', 'community', '{self-improvement,finance,literacy}', 'MIT', 'published'),
('Relationship Improvement', 'Create a relationship improvement plan:\n\nRelationship: [type]\nFocus: [area]\n\nInclude:\n1. Communication skills\n2. Quality time\n3. Conflict resolution\n4. Appreciation practices\n5. Growth together', 'prompt', 'community', '{self-improvement,relationships,communication}', 'MIT', 'published'),
('Career Development', 'Create a career development plan:\n\nCurrent role: [description]\nGoal: [target]\n\nInclude:\n1. Skills gap analysis\n2. Learning path\n3. Networking strategy\n4. Portfolio building\n5. Timeline', 'prompt', 'community', '{self-improvement,career,development}', 'MIT', 'published'),
('Creativity Boost', 'Create a creativity boosting routine:\n\nField: [art/writing/etc]\n\nInclude:\n1. Daily exercises\n2. Inspiration sources\n3. Creative constraints\n4. Collaboration\n5. Output goals', 'prompt', 'community', '{self-improvement,creativity,routine}', 'MIT', 'published'),
('Digital Detox Plan', 'Create a digital detox plan:\n\nCurrent usage: [description]\nGoals: [specific]\n\nInclude:\n1. Screen time limits\n2. Alternative activities\n3. Notification management\n4. Social media boundaries\n5. Reintroduction plan', 'prompt', 'community', '{self-improvement,digital,detox}', 'MIT', 'published'),
('Memory Improvement', 'Create a memory improvement plan:\n\nFocus: [type]\n\nInclude:\n1. Memory techniques\n2. Practice exercises\n3. Lifestyle factors\n4. Tools/aids\n5. Progress tracking', 'prompt', 'community', '{self-improvement,memory,brain}', 'MIT', 'published'),
('Leadership Development', 'Create a leadership development plan:\n\nCurrent role: [description]\nGoal: [target]\n\nInclude:\n1. Leadership style\n2. Skill development\n3. Mentorship\n4. Practice opportunities\n5. Feedback mechanisms', 'prompt', 'community', '{self-improvement,leadership,development}', 'MIT', 'published'),
('Work-Life Balance', 'Create a work-life balance plan:\n\nCurrent situation: [description]\n\nInclude:\n1. Boundary setting\n2. Time management\n3. Energy management\n4. Priority alignment\n5. Adjustment strategies', 'prompt', 'community', '{self-improvement,balance,wellness}', 'MIT', 'published'),
('Overcoming Procrastination', 'Create a procrastination overcoming plan:\n\nPatterns: [description]\n\nInclude:\n1. Root cause analysis\n2. Task breakdown\n3. Accountability systems\n4. Reward mechanisms\n5. Environment design', 'prompt', 'community', '{self-improvement,procrastination,productivity}', 'MIT', 'published'),
('Gratitude Practice', 'Create a gratitude practice:\n\nCurrent level: [beginner/experienced]\n\nInclude:\n1. Daily prompts\n2. Weekly reflection\n3. Expression methods\n4. Sharing practices\n5. Impact tracking', 'prompt', 'community', '{self-improvement,gratitude,mindfulness}', 'MIT', 'published'),
('Life Vision Board', 'Create a life vision:\n\nTimeframe: [1/5/10 years]\n\nInclude:\n1. Career vision\n2. Relationships\n3. Health\n4. Finances\n5. Personal growth', 'prompt', 'community', '{self-improvement,vision,planning}', 'MIT', 'published')
on conflict do nothing;

-- Business Strategy Category (20 prompts)
insert into prompts (title, content, type, author_name, tags, license, status) values
('SWOT Analysis', 'Conduct a SWOT analysis for:\n\nBusiness: [description]\n\nInclude:\n1. Strengths\n2. Weaknesses\n3. Opportunities\n4. Threats\n5. Strategic implications', 'prompt', 'community', '{strategy,swot,analysis}', 'MIT', 'published'),
('Porter''s Five Forces', 'Analyze industry forces for:\n\nIndustry: [description]\n\nInclude:\n1. Competitive rivalry\n2. Supplier power\n3. Buyer power\n4. Threat of substitution\n5. Threat of new entry', 'prompt', 'community', '{strategy,porter,analysis}', 'MIT', 'published'),
('Blue Ocean Strategy', 'Identify blue ocean opportunities for:\n\nMarket: [description]\n\nInclude:\n1. Value innovation\n2. Eliminate-reduce-raise-create grid\n3. New market space\n4. Strategic canvas\n5. Implementation roadmap', 'prompt', 'community', '{strategy,blue-ocean,innovation}', 'MIT', 'published'),
('Growth Hacking Plan', 'Create a growth hacking plan for:\n\nProduct: [description]\n\nInclude:\n1. Acquisition channels\n2. Activation tactics\n3. Retention strategies\n4. Revenue optimization\n5. Referral programs', 'prompt', 'community', '{strategy,growth,hacking}', 'MIT', 'published'),
('Lean Startup Canvas', 'Create a lean startup canvas for:\n\nIdea: [description]\n\nInclude:\n1. Problem\n2. Solution\n3. Key metrics\n4. Unique value proposition\n5. Unfair advantage', 'prompt', 'community', '{strategy,lean,startup}', 'MIT', 'published'),
('Pitch Deck Creator', 'Create a pitch deck outline for:\n\nStartup: [description]\n\nInclude:\n1. Problem slide\n2. Solution slide\n3. Market size\n4. Traction\n5. Team slide', 'prompt', 'community', '{strategy,pitch,deck}', 'MIT', 'published'),
('Financial Model Builder', 'Build a financial model for:\n\nBusiness: [description]\n\nInclude:\n1. Revenue projections\n2. Cost structure\n3. Break-even analysis\n4. Cash flow\n5. Key assumptions', 'prompt', 'community', '{strategy,finance,model}', 'MIT', 'published'),
('Exit Strategy Planner', 'Plan an exit strategy for:\n\nBusiness: [description]\n\nInclude:\n1. Exit options\n2. Valuation methods\n3. Timeline\n4. Preparation steps\n5. Stakeholder management', 'prompt', 'community', '{strategy,exit,planning}', 'MIT', 'published'),
('International Expansion', 'Plan international expansion for:\n\nBusiness: [description]\nTarget markets: [list]\n\nInclude:\n1. Market selection\n2. Entry strategy\n3. Localization\n4. Compliance\n5. Operations', 'prompt', 'community', '{strategy,international,expansion}', 'MIT', 'published'),
('Mergers & Acquisitions', 'Analyze M&A opportunities for:\n\nCompany: [description]\n\nInclude:\n1. Target identification\n2. Valuation\n3. Due diligence\n4. Integration plan\n5. Risk assessment', 'prompt', 'community', '{strategy,ma,acquisition}', 'MIT', 'published'),
('Turnaround Strategy', 'Create a turnaround strategy for:\n\nBusiness: [description]\n\nInclude:\n1. Situation analysis\n2. Quick wins\n3. Restructuring\n4. Stakeholder management\n5. Recovery timeline', 'prompt', 'community', '{strategy,turnaround,recovery}', 'MIT', 'published'),
('Product Roadmap', 'Create a product roadmap for:\n\nProduct: [description]\n\nInclude:\n1. Vision\n2. Themes\n3. Features\n4. Timeline\n5. Success metrics', 'prompt', 'community', '{strategy,product,roadmap}', 'MIT', 'published'),
('Customer Journey Map', 'Map the customer journey for:\n\nProduct: [description]\n\nInclude:\n1. Awareness\n2. Consideration\n3. Purchase\n4. Retention\n5. Advocacy', 'prompt', 'community', '{strategy,customer,journey}', 'MIT', 'published'),
('Value Proposition Design', 'Design a value proposition for:\n\nProduct: [description]\n\nInclude:\n1. Customer jobs\n2. Pains\n3. Gains\n4. Value map\n5. Fit analysis', 'prompt', 'community', '{strategy,value,proposition}', 'MIT', 'published'),
('Strategic Partnerships', 'Identify strategic partnerships for:\n\nBusiness: [description]\n\nInclude:\n1. Partner criteria\n2. Target list\n3. Value exchange\n4. Outreach approach\n5. Partnership structure', 'prompt', 'community', '{strategy,partnership,alliance}', 'MIT', 'published'),
('Risk Management Plan', 'Create a risk management plan for:\n\nBusiness: [description]\n\nInclude:\n1. Risk identification\n2. Impact assessment\n3. Mitigation strategies\n4. Monitoring\n5. Response plans', 'prompt', 'community', '{strategy,risk,management}', 'MIT', 'published'),
('Innovation Framework', 'Create an innovation framework for:\n\nOrganization: [description]\n\nInclude:\n1. Innovation types\n2. Process\n3. Culture\n4. Resources\n5. Metrics', 'prompt', 'community', '{strategy,innovation,framework}', 'MIT', 'published'),
('Competitive Strategy', 'Develop a competitive strategy for:\n\nBusiness: [description]\n\nInclude:\n1. Competitive advantage\n2. Positioning\n3. Differentiation\n4. Defense tactics\n5. Offensive moves', 'prompt', 'community', '{strategy,competitive,positioning}', 'MIT', 'published'),
('Sustainability Strategy', 'Create a sustainability strategy for:\n\nBusiness: [description]\n\nInclude:\n1. Environmental impact\n2. Social responsibility\n3. Economic viability\n4. Reporting\n5. Improvement roadmap', 'prompt', 'community', '{strategy,sustainability,esg}', 'MIT', 'published'),
('Digital Transformation', 'Plan digital transformation for:\n\nOrganization: [description]\n\nInclude:\n1. Current state\n2. Vision\n3. Technology roadmap\n4. Change management\n5. Success metrics', 'prompt', 'community', '{strategy,digital,transformation}', 'MIT', 'published')
on conflict do nothing;
